name: End to End Test Suite

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Check if a cache matching the checksums of all repos being tested exists
      - name: Check if a cache exists
        run: echo Not yet implemented.

      - name: Setup Hyde Environment
        run: bash setup.sh

      - name: Cache Hyde Environment
        run: echo Not yet implemented.

      - name: Upload Environment Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hyde-environment
          path: |
            hyde
            !hyde/vendor
            !hyde/node_modules
      - name: Upload Setup Log
        uses: actions/upload-artifact@v3
        with:
          name: hyde-setup-script.log
          path: latest.log

  run-phpunit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: hyde-environment
          path: hyde

      - name: Install dependencies from lock file
        run: cd hyde && composer install

      - name: Run PHPUnit tests
        run: cd hyde && vendor/bin/pest

  build-static-site:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
  
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: hyde-environment
          path: hyde

      - name: Install composer dependencies from lock file
        run: cd hyde && composer install
      
      - name: Install Node Modules
        run: cd hyde && npm install

      - name: Todo - download latest hydefront version
        run: echo Not yet implemented.

      - name: Publish test files
        run: bash publish-stubs.sh

      - name: Publish post feed homepage
        run:  php hyde publish:homepage posts --no-interaction

      - name: Build static site
        run: cd hyde && php hyde build --pretty --run-prod

      - name: Upload static site artifact
        uses: actions/upload-artifact@v3
        with:
          name: hyde-compiled-static-site
          path: hyde/_site
  
  run-cypress-tests:
    runs-on: ubuntu-latest
    needs: build-static-site
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: hyde-compiled-static-site

      - name: Verify files
        run: ls

      - name: Run Cypress tests
        run: echo Not yet implemented.
        # run: cd hyde && npm run cypress:run