name: End to End Test Suite

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Check if a cache matching the checksums of all repos being tested exists
      - name: Check if a cache exists
        run: echo Not yet implemented.

      - name: Setup Hyde environment
        run: bash setup.sh

      - name: Cache Hyde environment
        run: echo Not yet implemented.

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hyde-environment
          path: |
            hyde
            !hyde/vendor
            !hyde/node_modules

  run-phpunit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: hyde-environment
          path: hyde

      - name: Install dependencies from lock file
        run: cd hyde && composer install

      - name: Run PHPUnit tests
        run: cd hyde && vendor/bin/pest

  run-cypress-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
  
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: hyde-environment
          path: hyde

      - name: Install dependencies from lock file
        run: cd hyde && composer install

      - name: Publish test files
        run: bash publish-stubs.sh

      - name: Run Cypress tests
        run: echo Not yet implemented.
        # run: cd hyde && npm run cypress:run
  